version: '2'

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=8000
      - MONGODB_CNN= mongodb://localhost:27017
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
