version: '3'

services:
  tutor:
    build: ./Microservicios/tutor-servicio
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN= mongodb://localhost:27017/
  tutorado:
    build: ./Microservicios/tutorado-servicio
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN= mongodb://localhost:27017/tutorado-servicio

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tutor
      - tutorado

  mongo:
    image: mongo
    ports:
      - "27017:27017"
